"""What `mount_ledger_tables` promises about shapes, prefixes and isolation (ADR-0050).

The development plan names two likely failure modes for this phase, and both are defended against
structurally here rather than noticed later: *index names colliding without the prefix* (the
two-prefixes-one-metadata test), and *dialect-specific types* (the portable-column-types test,
with the host's autogenerated revision checked in ``test_hostapp.py``).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
import sqlalchemy as sa
from baseaicore import TokenUsage

from conftest import MIDDAY, ManualClock, mounted, session_factory_for
from loadledger import BudgetCeiling, CeilingScope, Debit
from loadledger.sql import DEFAULT_TABLE_PREFIX, SqlLedger, mount_ledger_tables

if TYPE_CHECKING:
    from sqlalchemy import Engine

PORTABLE_TYPES = {"String", "Text", "BigInteger", "Boolean", "DateTime"}
"""Every column type these tables are allowed to use.

Deliberately small, and all five are SQLAlchemy *generic* types. A generic type renders per
dialect and Alembic renders it back as ``sa.<Name>()``, so the host's autogenerated revision runs
unchanged on both. A type imported from ``sqlalchemy.dialects.*`` — ``JSONB``, ``UUID``, a
PostgreSQL ``ENUM`` — renders into the revision as ``postgresql.JSONB()`` and takes the host's
migration history with it onto one dialect.
"""

ACCUMULATING_COLUMNS = {
    "tokens_spent",
    "nanos_spent",
    "unpriced_debit_count",
    "untotalled_debit_count",
    "unmetered_debit_count",
}
"""Columns that grow without bound, and must therefore be 8 bytes wide. See the module docstring
of ``loadledger.sql``: $2.15 is 2 150 000 000 nanos, already past a 4-byte integer."""


def test_the_default_prefix_is_the_documented_one() -> None:
    tables = mount_ledger_tables(sa.MetaData())
    assert DEFAULT_TABLE_PREFIX == "ledger_"
    assert [table.name for table in tables.all_tables] == [
        "ledger_entries",
        "ledger_balances",
        "ledger_balance_money",
        "ledger_runs",
    ]


def test_two_prefixes_mount_into_one_metadata_without_colliding() -> None:
    """The concrete form of "index names colliding without the prefix".

    One ``MetaData`` is what a host has. If a second mount reused an index or constraint name, this
    would raise here — and on PostgreSQL, where index names are unique per schema, it would raise
    at ``upgrade`` time in production instead.
    """
    metadata = sa.MetaData()
    first = mount_ledger_tables(metadata, prefix="ledger_")
    second = mount_ledger_tables(metadata, prefix="trial_")

    every_name: list[str] = []
    for tables in (first, second):
        names: list[str] = []
        for table in tables.all_tables:
            names.append(table.name)
            names.extend(str(index.name) for index in table.indexes)
            names.extend(str(constraint.name) for constraint in table.constraints)
        every_name.extend(names)
        # Strip the kind marker Alembic and PostgreSQL both care about, then the prefix must be
        # all that is left in front.
        for name in names:
            bare = name.removeprefix("pk_").removeprefix("ix_")
            assert bare.startswith(tables.prefix), f"{name} does not carry {tables.prefix!r}"
    assert len(every_name) == len(set(every_name)), sorted(every_name)


def test_mounting_the_same_prefix_twice_into_one_metadata_is_refused() -> None:
    metadata = sa.MetaData()
    mount_ledger_tables(metadata)
    with pytest.raises(sa.exc.InvalidRequestError, match="already defined"):
        mount_ledger_tables(metadata)


@pytest.mark.parametrize("prefix", ["", "1ledger_", "ledger-", "ledger table_", "läd_"])
def test_a_prefix_that_is_not_an_identifier_is_refused(prefix: str) -> None:
    with pytest.raises(ValueError, match="prefix"):
        mount_ledger_tables(sa.MetaData(), prefix=prefix)


def test_every_column_type_is_portable_across_both_dialects() -> None:
    tables = mount_ledger_tables(sa.MetaData())
    sqlite = sa.dialects.sqlite.dialect()
    postgresql = sa.dialects.postgresql.dialect()  # type: ignore[no-untyped-call] # SQLAlchemy
    for table in tables.all_tables:
        for column in table.columns:
            kind = type(column.type)
            where = f"{table.name}.{column.name}"
            assert kind.__module__ == "sqlalchemy.sql.sqltypes", (
                f"{where} uses {kind.__module__}.{kind.__name__}, which is dialect-specific and "
                "would render into a host's autogenerated revision as such"
            )
            assert kind.__name__ in PORTABLE_TYPES, f"{where} is {kind.__name__}"
            # And both dialects can actually render DDL for it.
            assert column.type.compile(sqlite)
            assert column.type.compile(postgresql)


def test_every_accumulating_column_is_eight_bytes_wide() -> None:
    tables = mount_ledger_tables(sa.MetaData())
    seen = set()
    for table in tables.all_tables:
        for column in table.columns:
            if column.name in ACCUMULATING_COLUMNS:
                seen.add(column.name)
                assert isinstance(column.type, sa.BigInteger), (
                    f"{table.name}.{column.name} accumulates and must be BigInteger: "
                    "$2.15 is 2 150 000 000 nanos, past a 4-byte integer, and PostgreSQL enforces "
                    "the width where SQLite does not"
                )
    assert seen == ACCUMULATING_COLUMNS


def test_no_foreign_key_leaves_the_mounted_set() -> None:
    """ADR-0050 decision 2: no relationship to an application's entities, in either direction."""
    tables = mount_ledger_tables(sa.MetaData())
    for table in tables.all_tables:
        assert table.foreign_keys == set()


def test_the_handle_points_at_the_metadata_the_host_passed() -> None:
    metadata = sa.MetaData()
    tables = mount_ledger_tables(metadata, prefix="budget_")
    assert tables.metadata is metadata
    assert tables.prefix == "budget_"
    assert set(metadata.tables) == {table.name for table in tables.all_tables}


def test_the_tables_create_and_round_trip_on_both_dialects(engine: Engine) -> None:
    _, tables = mounted(engine, prefix="budget_")
    inspector = sa.inspect(engine)
    assert set(inspector.get_table_names()) >= {table.name for table in tables.all_tables}

    ledger = SqlLedger(
        session_factory_for(engine),
        [BudgetCeiling(scope=CeilingScope.PER_RUN, tokens=10_000)],
        clock=ManualClock(),
        table_prefix="budget_",
    )
    # The ledger builds its statements against the same shapes, under the same prefix.
    assert ledger.tables.prefix == "budget_"
    assert [table.name for table in ledger.tables.all_tables] == [
        table.name for table in tables.all_tables
    ]

    ledger.debit(
        Debit(
            run_id="traj-1",
            source_ref="turn-1",
            usage=TokenUsage(input_tokens=5, output_tokens=5),
            cost=None,
            occurred_at=MIDDAY,
        )
    )
    assert ledger.remaining("traj-1")[0].tokens_spent == 10


def test_two_hosts_two_databases_one_package_version_do_not_see_each_other(
    tmp_path_factory: pytest.TempPathFactory,
) -> None:
    """ "Two applications mounting these tables have two tables in two databases — never one."

    Different prefixes *and* different files, because both are how a host keeps its ledger its
    own: the prefix separates them inside one schema, the file separates the schemas.
    """
    directory = tmp_path_factory.mktemp("two-hosts")
    ledgers = {}
    engines = {}
    for name, prefix in (("alpha", "ledger_"), ("beta", "budget_")):
        engine = sa.create_engine(f"sqlite:///{directory / f'{name}.sqlite3'}")
        engines[name] = engine
        mounted(engine, prefix=prefix)
        ledgers[name] = SqlLedger(
            session_factory_for(engine),
            [BudgetCeiling(scope=CeilingScope.PER_DAY, tokens=1_000_000)],
            clock=ManualClock(),
            table_prefix=prefix,
        )

    ledgers["alpha"].debit(
        Debit(
            run_id="shared-run-id",
            source_ref="turn-1",
            usage=TokenUsage(input_tokens=1_000, output_tokens=0),
            cost=None,
            occurred_at=MIDDAY,
        )
    )
    ledgers["beta"].declare_run("shared-run-id")

    # Same run id, same UTC day, same package version — and nothing crosses.
    assert ledgers["alpha"].remaining("shared-run-id")[0].tokens_spent == 1_000
    assert ledgers["beta"].remaining("shared-run-id")[0].tokens_spent == 0
    for name in engines:
        engines[name].dispose()


def test_the_package_creates_no_table_of_its_own_on_import() -> None:
    """No ``create_all`` in library code, ever (ADR-0050 decision 5).

    Reading the source is the only way to assert the absence of a call that would otherwise only
    show up as a table appearing in someone's database.
    """
    import ast
    from pathlib import Path

    import loadledger

    forbidden = {"create_all", "create_engine", "getenv", "environ", "connect", "run_migrations"}
    source_root = Path(loadledger.__file__).parent
    called: set[str] = set()
    for module in sorted(source_root.glob("*.py")):
        tree = ast.parse(module.read_text(encoding="utf-8"), filename=str(module))
        for node in ast.walk(tree):
            if isinstance(node, ast.Attribute) and node.attr in forbidden:
                called.add(f"{module.name}:{node.attr}")
            if isinstance(node, ast.Name) and node.id in forbidden:
                called.add(f"{module.name}:{node.id}")
    assert called == set(), (
        f"library code reaches for {sorted(called)} — the package owns no engine, no connection, "
        "no environment and no migration (ADR-0050 decisions 3 and 5)"
    )
